config/routes.rb
Rails.application.routes.draw do

  get 'searchs/search'
  root "homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create , :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    #collection do
    #  get :following, :followers
    #end
  end

  get "search" => "searches#search"

  #resources :relationships, only:[:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end


  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_stats.html.erb
<th>
  <% user ||= current_user %>
  <%= link_to user_followings_path(user) do %>
    <%= user.followings.count %>following
  <% end %>
</th>
<th>
  <%= link_to user_followers_path(user) do %>
    <%= user.followers.count %>followers
  <% end %>
</th>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
  <%= render "users/follow_list" , users: @users %>

app/views/relationships/followings.html.erb
<h2>Followings User</h2>
  <%= render "users/follow_list" , users: @users %>