config/routes.rb
Rails.application.routes.draw do

  get 'searchs/search'
  root "homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create , :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    #collection do
    #  get :following, :followers
    #end
  end

  get "search" => "searches#search"

  #resources :relationships, only:[:create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end

  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/search.html.erb
<h2>Results</h2>

<table class="table">
  <% if @range == "User" %>
    <thead>
      <tr>
        <th></th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
  <% else %>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= image_tag book.user.get_profile_image, size: '50x50' %></td>
          <td><%= link_to book_path(book) do %>
              <%= book.title %>
              <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>